//Used to detect when the CTRL key is pressed
var ctrlDown;

//Used to detect when the TAB key is pressed
var tabDown;

//Used to detect a delete button has been pressed
var scrollToElementAddedByAJAX = false;

$(document).ready(function() {
	//Remove browser validation
	//This is not currently needed to prevent the validation, but it might be
	//if digiforms is updated to use submit buttons
	//It is however necessary in order to prevent red borders around inputs
	//(in some browsers, e.g. firefox)
	preventBrowserFormActions();
	
	//Events used to check if control or tab is pressed
	initGlobalKeyEventListener();
	
	//Form elements
	formControlEventbinding();

	//Accordions
	initAccordions();

	//Skip nav 
	navigateToMainContentEventBinding();

	//Adjustments to the auto generated parts of the DOM
	adjustAutoGeneratedElements();

	//Event bindings that uses external APIs
	bindEventsThatCallsExternalAPIs();

	//Event bindings used for special validation
	validation();

	//Scrolls the first input with an error into view
	scrollToFirstError();

	//Adjust hrefs for file-download links
	initFileDownloads();

	//Disables add buttons when maxium number of
	//elements has been added
	disableAddButtonsWhenMaxIsReached();
	
	//Sets ARIA attributes for delete buttons
	setAriaAttributesForDeleteButtons();
	
	//Bind events / adjust eventhandlers to elements
	//that triggers ajax update
	initAJAXUpdateElements();
});

function preventBrowserFormActions() {
	$("#frm").attr("novalidate", "novalidate");
}

function browserIsIEOnWindowsPhone() {
	return navigator.userAgent.match(/IEMobile/i) || navigator.userAgent.match(/WPDesktop/i);
}

function initGlobalKeyEventListener() {
	
	//Checks if the CTRL key is pressed
	ctrlDown = false;

	$(document).on("keydown", function(event) {
		var key = event.keyCode || event.charCode;
		if (key == 17) {
			ctrlDown = true;
		}
	});

	$(document).on("keyup", function(event) {
		var key = event.keyCode || event.charCode;
		if (key == 17) {
			ctrlDown = false;
		}
	});
	
	//Checks if the TAB key is pressed
	tabDown = false;

	$(document).on("keydown", function(event) {
		var key = event.keyCode || event.charCode;
		if (key == 9) {
			tabDown = true;
		}
	});

	$(document).on("keyup", function(event) {
		var key = event.keyCode || event.charCode;
		if (key == 9) {
			tabDown = false;
		}
	});
}

function initCheckBoxesAndRadios() {
	$(".label_text").on("click", function(e) {
	    if (e.target.localName != "label") {
	    	var $checkbox = $(this).parent().find("input:checkbox");
	    	$checkbox.trigger("click");

	    	var $radio = $(this).parent().find("input:radio");
	    	$radio.trigger("click");
	    }
	});

	var toggleCheck = function($input) {
		if ($input.is(":checked")) {
	        $input.parent().siblings(".label_text").addClass("checked");
	    }
	    else {
	    	$input.parent().siblings(".label_text").removeClass("checked");
	    }
	};

	$(".control input:checkbox").on("change", function() {
		toggleCheck($(this));
	});

	//To ensure that all pseudo-elements are marked as checked when re-visiting a form
	var $checkboxes = $(".control input:checkbox:checked");
	$.each($checkboxes, function() {
		toggleCheck($(this));
	});

	$(".control input:radio").on("change", function() {
		var $allRadiosInFieldset = $(this).closest("fieldset").find("input:radio");
		$.each($allRadiosInFieldset, function() {
			toggleCheck($(this));
		});
	});
	var $radios = $("input:radio");
	$.each($radios, function() {
	  toggleCheck($(this));
	});


	//Focus (for accessibility)
	$(".control input").on("focus", function() {
		$(this).parent().parent().addClass("focused");
	});

	$(".control input").on("blur", function() {
		$(this).parent().parent().removeClass("focused");
	});

	$(".control input").on("change", function() {
		if($(this).is(":checked")) {
			$(this).closest(".control-container").find(".digiforms_validation_message:first").hide();
		}
	});
}

function initHelptexts() {
	//First hide all the help texts
	var $helpTexts = $(".help-text").hide();
	$helpTexts.attr("aria-hidden", "true");

	var $helpBtns = $(".btn-help");
	$helpBtns.attr("aria-label", "Hva menes med dette?");
	$helpBtns.attr("aria-expanded", "false");

	$.each($helpBtns, function() {
		var $helpElementsForInputs = $(this).closest(".help-elements-for-input").parent();

		var $correspondingDescription = "";

		if($helpElementsForInputs.length) {
			$correspondingDescription = $helpElementsForInputs.find("label:first");
			$correspondingDescription.attr("id", $correspondingDescription.attr("for") + "-" + $correspondingDescription.text().split("*")[0].trim())
		}
		else {
			$correspondingDescription = $(this).closest(".help-elements-for-fieldset").parent().find("legend:first");
			$correspondingDescription.removeClass("control-container-tight");
		}
		
		$(this).attr("aria-describedby", $correspondingDescription.attr("id"));
		
		$(this).attr("aria-controls", $(this).siblings(".help-text:first").attr("id"));
	});

	//Bind evnts 
	$helpBtns.on("click", function() {
		$(this).toggleClass("active");
		
		var $helpText = $(this).next(".help-text");

		$helpText.toggle();
		
		if ($helpText.is(":visible")) {
			$helpBtns.attr("aria-label", "Lukk hjelpetekst");
			$helpText.attr("aria-hidden", "false");
			$helpBtns.attr("aria-expanded", "true");
		} 
		else {
			$helpBtns.attr("aria-label", "Hva menes med dette?");
			$helpText.attr("aria-hidden", "true");
			$helpBtns.attr("aria-expanded", "false");
		}	
	});
}

//Takes a string and inserts the given
//mask when the function maskHere() returns true
//The parameter x is optional in the function maskHere()
//But is required in this function
function formatAfterInput(str, maxlength, mask, maskHere, x) {
	var valTrimmed = removeWhiteSpaces(str);
	var lastSliceIndex = 0;
	var newVal = "";
	for(var i = x; i < valTrimmed.length; i++) { //Make sure to prevent array out of bounds
		if (maskHere(i, x)) {
			newVal += valTrimmed.substring(lastSliceIndex, i) + mask;
			lastSliceIndex = i;
		}
	}
	newVal += valTrimmed.substring(lastSliceIndex, valTrimmed.length);
	return newVal.substring(0, maxlength);
}

//Pads the given string with a space, by x characters
function padBy(x, str, maxlength) {
	return formatAfterInput(str, maxlength, " ", function(i, x) { return i % x == 0; }, x);
}

function initInputs() {
	//Bring up the numeric keypad for iOS and Android
	$("input.numeric-text").attr("pattern", "[0-9]*"); //iOS
	$("input.numeric-text").attr("inputmode", "numeric"); //Android
	
	//Checks if keyCode is numeric
	//Allows keycodes are defined by the array "exceptionKeyCodes"
	var isNumericKey = function(keyCode, exceptionKeyCodes) {
		//console.log("keyCode is: " + keyCode + " exceptions are: '" + exceptionKeyCodes + "'" + " keyCode in array: " + $.inArray(keyCode, exceptionKeyCodes));
		if (browserIsIEOnWindowsPhone() || (keyCode >= 48 && keyCode <= 57) || (keyCode >= 96 && keyCode <= 105) || (exceptionKeyCodes != undefined && $.inArray(keyCode, exceptionKeyCodes) > -1)) {
			return true;
		}
		return false;
	}
	
	//Clears all non-numeric input from the input field
	//Skips characters defined by the string "exceptions"
	var clearNonNumericInput = function($input, exceptions) {
		if(!browserIsIEOnWindowsPhone()) {
			var currentVal = $input.val();
			var newVal = "";
			for(var i = 0 ; i < currentVal.length; i++) {
				var c = currentVal.charAt(i);
				if ($.isNumeric(c) || (exceptions != undefined && exceptions.indexOf(c) > -1)) {
					newVal += c;
				}
			}
			$input.val(newVal);
		}
	}
	
	$("input.numeric-text").on("keyup", function() {
		clearNonNumericInput($(this), " ");
	});
	
	//Prevents user from entering non-numeric input
	$("input.numeric-text").on("keydown", function(event) {
		var key = event.keyCode || event.charCode;
		if (userIsTyping($(this), event) && !isNumericKey(key)) {
			event.preventDefault();
		}
	});

	//Function used to insert a string at a specific index
	//Used when formatting input immediately when input is entered
	function maskAt(indexStop, mask, $input) {
		if ($input.val().charAt(indexStop - 1) == mask) return;
		$input.val($input.val().substring(0, indexStop) + mask + $input.val().substring(indexStop, parseInt($input.attr("maxlength"))));
	}

	//Checks if key was delete, backspace, arrows, shift, ctrl, tab, home or end key
	function isEditKeyEvent(event) {
		if (ctrlDown) return true;
		var key = event.keyCode || event.charCode;
		if(key != 8 && key != 9 && key != 46 && key != 16 && key != 17 && key != 19 && (key < 35 || key > 40)) return false;
		return true;
	}

	//Function used to determine if a user is typing
	function userIsTyping($element, event) {
		return !isEditKeyEvent(event) && $element.val().length < parseInt($element.attr("maxlength")) && parseInt($element.prop("selectionStart")) == parseInt($element.prop("selectionEnd"));
	}

	//Input masking for norwegian account numbers - regular input (keys)
	$("input.numeric-text.account-mask").on("keydown", function(event) {
		if(!browserIsIEOnWindowsPhone()) {
			var mask = " ";
			//Don't mess with value on delete, backspace, arrows, shift, ctrl, home or end key
	    	if(userIsTyping($(this), event)) {
	    		var thisVal = $(this).val();
				if (thisVal.length == 4 || thisVal.length == 7) {
					maskAt(thisVal.length, mask, $(this));
				}
	    	}
    	}
	});
	$("input.account-mask").on("change paste", function() {
    	var $this = $(this);
    	setTimeout(function () {
			clearNonNumericInput($this);
    		$this.val(formatAfterInput($this.val(), $this.attr("maxlength"), " ", function(i, x) { return i == 4 || i == 6; }, 0));
    	}, 100);
    });

	//Input masking for VPS account numbers - regular input (keys)
	$("input.vps-account-mask").on("keydown", function(event) {
		if(!browserIsIEOnWindowsPhone()) {
			//Don't mess with value on delete, backspace, arrows, shift, ctrl, home or end key
	    	if(userIsTyping($(this), event)) {
	    		var thisVal = $(this).val();
				if (thisVal.length == 5) {
					maskAt(thisVal.length, " ", $(this));
				}
	    	}
    	}
	});
    $("input.vps-account-mask").on("change paste", function() {
    	var $this = $(this);
    	setTimeout(function () {
			clearNonNumericInput($this);
    		$this.val(formatAfterInput($this.val(), $this.attr("maxlength"), " ", function(i, x) { return i == 5; }, 0));
    	}, 100);
    });

	//Phone numbers
	$('input[type="tel"]').on("keyup", function() {
		clearNonNumericInput($(this), "+-() ");
	});

	//Input masking for phone numbers
	//Sets the following format to the input: {000 00 000}
	//on key down (except for when "edit keys" are pressed)
	$('input[type="tel"]').on("keydown", function(event) {
		if(!browserIsIEOnWindowsPhone()) {
			//Don't mess with value on delete, backspace, arrows, shift, ctrl, home or end key
	    	if(userIsTyping($(this), event)) {
				var key = event.keyCode || event.charCode;
				if (!isNumericKey(key, [32, 40, 41, 107, 109, 187, 189])) { //Don't remove characters: " ()+-"
					event.preventDefault();
				}
	    		var thisVal = $(this).val();
				var index = thisVal.length - getSplitIndexForPhoneNumber(thisVal);

				if (index == 3 || index == 6 || (index > 9 && (index + 2) % 4 == 0)) {
					maskAt(thisVal.length, " ", $(this));
				}
	    	}
    	}
	});

	//Sets the following format to the input: {000 00 000}
	//on change or paste
	$('input[type="tel"]').on("change paste", function() {
    	var $this = $(this);
    	setTimeout(function () {
			clearNonNumericInput($this, "+-() ");
    		var prefix = $this.val().substring(0, getSplitIndexForPhoneNumber($this.val()));
    		$this.val(prefix + formatAfterInput($this.val().substring(getSplitIndexForPhoneNumber($this.val()), $this.val().length), $this.attr("maxlength"), " ", function(i, x) {
    			return i == 3 || i == 5 || (i > 7 && (i + 1) % 3 == 0);
    		}, 0));
    	}, 100);
    });

	//Used to set the marker at the end of the prefilled input
	//(e.g country code for phone numbers)
	$(".prevent-select-on-tab").on("keyup", function(event)  {
 		var key = event.keyCode || event.charCode;
 		if (key == 9) {
 			$(this).prop("selectionStart", $(this).prop("selectionEnd"));
 		}
 	});
	$(".prevent-select-on-tab").on("focus", function(event)  {
		if (tabDown || $(this).prop("selectionStart") != $(this).prop("selectionEnd")) {
			$(this).prop("selectionStart", $(this).prop("selectionEnd"));
		}
 	});

	//Sets the following format to the input: {000 000 000}
	//on key down (except for when "edit keys" are pressed)
	$(".pad-3-by-3").on("keydown", function(event) {
		if(!browserIsIEOnWindowsPhone()) {
			//Don't mess with value on delete, backspace, arrows, shift, ctrl, home or end key
	    	if(userIsTyping($(this), event)) {
	    		var thisVal = $(this).val();
				if ((thisVal.length + 1) % 4 == 0) {
					maskAt(thisVal.length, " ", $(this));
				}
	    	}
    	}
    });

	//Sets the following format to the input: {000 000 000}
	//on change or paste
    $(".pad-3-by-3").on("change paste", function() {
    	var $this = $(this);
    	setTimeout(function () {
			clearNonNumericInput($this);
    		$this.val(padBy(3, $this.val(), $this.attr("maxlength")));
    	}, 100);
    });

    $(".input-percentage").on("change", function() {
    	var val = parseFloat($(this).val());
    	var max = $(this).attr("max");
    	var min = $(this).attr("min");
    	if(val <= max && val >= min) {
    		$(this).parent().parent().siblings("input[type=hidden]").val("true");
    	}
    	else {
    		$(this).parent().parent().siblings("input[type=hidden]").val("false");
    	}
    	$(this).val(val.toString());
    });
}

function formControlEventbinding() {
	initCheckBoxesAndRadios();
	initHelptexts(); 
	initInputs();
}

//Sets focus (focus()) doesn't work on mobile devices)
function focusMobile($element) {
	$element.on('touchstart', function() {
    	$(this).focus();
  	});
}

//Scrolles selected element into view
function scrollTo($element, delay) {
	if ($element.length > 0) {
		$('html, body').animate({
        	scrollTop: $element.offset().top
    	}, delay);
	}
}

function toggleARIAPropertiesForAccordion($accBtn) {
	var expanded = $accBtn.attr("aria-expanded");

	var ariaExpandedAttr = expanded == "false" ? "true" : "false";
	$accBtn.attr("aria-expanded", ariaExpandedAttr);

	var $correspondingPanel = $accBtn.siblings(".panel:first");
	var ariaHiddenAttr = expanded;
	$correspondingPanel.attr("aria-hidden", ariaHiddenAttr);
}


function addARIAPropertiesToAccordion($accBtn) {
	var $correspondingPanel = $accBtn.siblings(".panel:first");

	$accBtn.attr("aria-controls", $correspondingPanel.attr("id"));
	$accBtn.attr("aria-expanded", "false");

	$correspondingPanel.attr("aria-hidden", "true");
}

function openAccordionsWithErrors($panels) {
	$.each($panels, function() {
		if (getFirstError($(this)).length) {
			var $correspondingButton = $(this).siblings(".accordion:first");
			if (!$correspondingButton.hasClass(".active")) {
				$correspondingButton.click();
			}
		}
	});	
}

function scrollToLastUnfinnishedAccordion($panels) {
	//If the form has an error: open all the accordions with errors
	if (getFirstError($("#main-content_content")).length) {
		openAccordionsWithErrors($panels);
	}
	else {//If not: scroll to and open the last accordion added
		var $lastAccordionContainer = $(".focus-last-child .accordion-container").last();
		var $lastAccordionBtn = $lastAccordionContainer.find(".accordion").first();
		if (!$lastAccordionBtn.hasClass("active")) {
			var blankFormInputs = false;
			$.each($lastAccordionContainer.find("input"), function() {
				if (!$(this).val()) {
					blankFormInputs = true;
					return false;
				}
			});
			if (blankFormInputs) {
				$lastAccordionBtn.click();
				scrollTo($lastAccordionContainer, 1000);
			}
		}
	}
}

function toggleAccordion($accBtn) {
	$accBtn.toggleClass("active");
	var $correspondingPanel = $accBtn.siblings(".panel").first();
	$correspondingPanel.toggleClass("hidden");
	toggleARIAPropertiesForAccordion($accBtn);
}

function initAccordionsAddedByAJAX() {
	var $accBtns = $(".load-container button.accordion");
	$.each($accBtns, function() {
		addARIAPropertiesToAccordion($(this));
	});
	
	//Appends attributes such as max/min to inputs
	//inside the panel of the accordion
	appendAttributesToNumberInputs();
	
	//Sets the text of the button to the same as the name of
	//the benefitial owner
	var setAccordionBtnTitle = function($accordionContainer) {
		var prefix = '<span class="chev"></span><span class="desc">';
		var suffix = "</span>";
		var title = $accordionContainer.find(".accordion-description").first().val();
		var $button = $accordionContainer.find("button.accordion");
		if (title != "") {
			$button.html(prefix + title + suffix);
		}
		else {
			var idSplit = $button.attr("id").split("_");
			$button.html(prefix + "Reell rettighetshaver " + (idSplit.length > 0 ? idSplit[idSplit.length - 1] : "") + suffix);
		}
	};
	
	$.each($(".load-container .set-name-accordion"), function() {
		setAccordionBtnTitle($(this));
	});

	$(".load-container .set-name-accordion .accordion-description").on("change", function() {
		setAccordionBtnTitle($(this).closest(".set-name-accordion"));
	});
	
	//Init for autofill country phone code
	//and city
	bindEventsThatCallsExternalAPIs();
	
	//Init number patterns
	initInputs();
	
	initDeleteButtons();
	
	//Prevent user from adding more items than allowed
	disableAddButtonsWhenMaxIsReached();
	
	//Scrolls to the last unfinnished accordion
	//(that has class "focus-last-child")
	var $panels = $(".load-container .accordion-container .panel");
	if (scrollToElementAddedByAJAX) {
		scrollToLastUnfinnishedAccordion($panels);
	}
	else if (getFirstError($("#main-content_content")).length) {
		openAccordionsWithErrors($panels);
	}
	scrollToElementAddedByAJAX = true;
}

function initAccordions() {
	var $panels = $(".accordion-container:not(.added-by-AJAX) .panel");
	//Panels
	$.each($panels, function() {
		if (!$(this).hasClass("hidden")) {
			$(this).addClass("hidden");
		}
	});
	
	//Buttons
	var $accBtns = $(".accordion-container:not(.added-by-AJAX) button.accordion");
	$.each($accBtns, function() {
		addARIAPropertiesToAccordion($(this));
	});
	$accBtns.on("click", function() {
		toggleAccordion($(this));
	});
	
	//Set aria attributes for edit buttons (that are inside summary accordions)
	$.each($(".accordion-container .summary-container"), function() {
		var $changeBtn = $(this).siblings(".btn-primary");
		$changeBtn.attr("aria-describedby", $(this).find("table").attr("aria-describedby"));
	});
}

//TODO - not currently needed or in use
function splitTextElegantly(text, nRows) {
	var words = text.split(" ");
	var nWords = words.length;
	var nCharacters = text.length;

	//console.log("split " + text + " in " + nRows + " rows. It has " + nWords + " words");

	if (nWords < nRows) {
		return text;
	}
	else if (nWords == nRows) {
		var newText = "";
		for(var i=0; i < nWords - 1; i++) {
			newText += words[i] + "<br>";
		}
		return newText += words[nWords - 1];
	}
	else {
		var mark = nCharacters / nRows; //Assume X / 2

		var newText = "";
		for(var i=nWords - 1; i > 0; i--) {
			newText = "<br>" + words[i]
		}
		return words[0].concat(newText);
	}
}

function navigateToMainContentEventBinding() {
	$("#skip-navigation a").on("click", function() {
		var $input = $("#main-content").find(":input[id]:first");

		setTimeout(function() {
			$input.focus()
		}, 100);
	});
}

//Appends attributes to number inputs, based on their classes
function appendAttributesToNumberInputs() {
	$(".input-decimal-2").attr("step", "0.01");
	$(".input-percentage").attr("min", "0");
	$(".input-percentage").attr("max", "100");
}

function adjustErrorMessageList() {
	$(".error-summary").hide();
	$.each($(".error-summary > div"), function(index) {
		var $firstChild = $(this).children(":first");
		var autoGeneratedHeadingSplit = $firstChild.text().split("(");

		var pageNumber = autoGeneratedHeadingSplit[0].split("page ").pop().trim();
		var heading = pageNumber + ". " + autoGeneratedHeadingSplit[1].split("-")[0];
		$firstChild.remove();
		$(this).prepend('<h4 id="error-heading-' + pageNumber + '">' + heading + "</h4>");
		$(this).addClass("panel panel-danger list-container");

		var $container = $(this);

		
		var documentName = "Swedbank_KYC";
		if($("title").text().split("-")[1].trim() == "Bedrift") {
			documentName += "_Bedrift";
		}

		//Variables used manipulate error text and style of 
		//benifital owners (to avoid identical text on links).
		//And adjust the layout so it's easier to read
		var prefixBenifitialOwners = "";
		var prevBenifitialOwner = "1";
		var errorsForBenifitialOwnersHasBeenListed = false;
		
		var sessionTagIndex = window.location.href.indexOf("xsessiontag");
		var getUrl = window.location.href.substring(0, sessionTagIndex) + "documentName=" + documentName + "&pageNumber=" + pageNumber;
		$.get(getUrl, function(data) {
			var trimmedData = data.substring(data.indexOf("<form"), data.indexOf("</form>") + 8);
			var $DOM = $($.parseHTML(trimmedData));
			
			//Updates some of the links in the list of errors
			$.each($container.find("ul li a"), function(index) {
				var fieldID = $(this).attr("href").split("#").pop().replace(".", "\\.");
				var $field = $DOM.find("#"+fieldID);
				if($field != undefined && $field.hasClass("control-validation")) {
					
					//Update error text
					var $correspondingLegend = $field.parent().siblings("legend");
					$(this).text($correspondingLegend.text() + " (" + $(this).text() + ")");
					
					//Make an exception for the question about PEP with
					//pep-text-container_legend (company only)
					if ($correspondingLegend.attr("id") == "pep-text-container_legend") {
						
						var $PEPLegendLink  = $(this);
						
						var getXMLUrl = window.location.href.replace("htmlViewer", "xmlData");
						$.get(getXMLUrl, function(xmlData) {
							
							var aktorerIBedriftenChilds = xmlData.getElementsByTagName("aktorer-i-bedriften")[0].childNodes;
							
							for (var i=0; i < aktorerIBedriftenChilds.length; i++) {
								
								//Update the text of the error message (the company does not have any benifital owners)
								if (aktorerIBedriftenChilds[i].nodeName == "reelle-rettighetshavere" && aktorerIBedriftenChilds[i].getAttribute("har") == "nei") {
									$PEPLegendLink.text($PEPLegendLink.text().replace("reelle rettighetshavere, ", ""));
								}
							}
						});
					}
					
					//Update the href so that it can be scrolled into view
					$(this).attr("href", $(this).attr("href").split("#")[0] + "#" + $correspondingLegend.attr("id"));
					
					//Add som margin-top if needed
					if (errorsForBenifitialOwnersHasBeenListed) {
						$(this).parent().css("margin-top", "3em");
						errorsForBenifitialOwnersHasBeenListed = false;
					}
				}
				else if ($(this).text().toLowerCase().indexOf("laste opp fullmakt") > -1) {
					$(this).attr("href", $(this).attr("href").split("#")[0] + "#fullmakt-container");
				}
				else if (heading.indexOf("Aktører i bedriften") > -1) {
					//Update error text
					var currentBenifitialOwner = $(this).attr("href").split("_").pop().trim();
					prefixBenifitialOwners = "Reell rettighetshaver " + currentBenifitialOwner + " - ";
					$(this).prepend(prefixBenifitialOwners);
					
					//Update the href so that it can be scrolled into view nicely
					//By making sure the label of the input is shown
					$(this).attr("href", $(this).attr("href").split("#")[0] + "#" + "container-" + $(this).attr("href").split("#").pop());
					
					//Add som margin-top if needed
					if (currentBenifitialOwner != prevBenifitialOwner) {
						$(this).parent().css("margin-top", "3em");
					}
					prevBenifitialOwner = currentBenifitialOwner;
					
					errorsForBenifitialOwnersHasBeenListed = true;
				}
				else if ($field.length) { 
					//Update the href so that it can be scrolled into view nicely
					//By making sure the label of the input is shown
					var $correspondingLabel = $field.parent().siblings(".label_text");
					$(this).attr("href", $(this).attr("href").split("#")[0] + "#" + $correspondingLabel.attr("id"));
				}
				//As by: https://www.w3.org/TR/WCAG20-TECHS/ARIA7
				//$(this).attr("aria-labelledby", "error-heading-"+ pageNumber); //Dette er antageligvis redundant
		  });
		});
	});
	$(".error-summary").prepend("<h3>Vi må be deg om å rette opp noen feil</h3>");
	$(".error-summary").show();
}

function adjustErrorMessages() {
	$.each($(".trim-errormsg .digiforms_validation_message"), function() {
		var newText = $(this).text().split("må").pop();
		$(this).text("Må" + newText);
	});
}

function appendAriaAttributesForPageSections() {
	//Landmarks for header
	$(".header").attr("role", "banner");
	
	//Landmarks for main
	$("#main-content").attr("role", "main");
	var $mainContentLabelledby = $("#main-content_legend");
	if ($mainContentLabelledby.length == 0) {
		$mainContentLabelledby = $("#main-content_heading");
	}
	$("#main-content").attr("aria-labelledby", $mainContentLabelledby.attr("id"));
	
	//Bottom nav
	$(".next-prev-nav").attr("role", "navigation");
	$(".next-prev-nav").attr("aria-label", "Forrige / Neste");
}

function changeTextOnChange() {
	var $togglePEPText = $("#pep-text-container").find("fieldset legend:first");
	$togglePEPText.text("Er noen av foretakets ");
	$togglePEPText.append('<span class="text-toggle">reelle rettighetshavere, </span>styremedlemmer, daglig leder eller kontaktperson(er) en Politisk Eksponert Person (PEP)?');
	$togglePEPText.append('<span class="asterix" aria-hidden="true"> *</span>');
	
	var $togglesText = $(".toggles-text-on-change");
	
	var toggle = function($toggleElement) {
		var idSplit = $toggleElement.attr("id").split("toggles-");
		var toggles = idSplit.pop().trim();
		var action = idSplit[0].replace("-", "").trim();
		
		if ($toggleElement.is(":checked")) {
			if (action == "show") {
				$("#" + toggles + " .text-toggle").show();
			}
			else if (action == "hide") {
				$("#" + toggles + " .text-toggle").hide();
			}
		}
	}
	
	$.each($togglesText, function() {
		toggle($(this));
	});
	
	$togglesText.on("change", function() {
		toggle($(this));
	});
}

function adjustAutoGeneratedElements() {
	//Fix duplicate id:s

	//Recursive function that updates the id of an element and all its children
	var updateDuplicateIds = function(elements) { 
		$.each(elements, function(i) {
			$(this).attr("id", $(this).parent().attr("id") + $(this).attr("id") + i)
	  		if ($(this).children().length > 0) {
	  			updateDuplicateIds($(this).children());
	  		}
		});
	}

	//Append asterixes
	appendAsterixToMandatoryFields();

	//Append attributes to number-inputs
	appendAttributesToNumberInputs();

	//Make adjustments to the error list on the last page
	adjustErrorMessageList();

	//Make adjustments to the error list on the last page
	adjustErrorMessages();
	
	//Add WAI-aria landmarks to page sections
	appendAriaAttributesForPageSections();
	
	//Toggles a text when
	changeTextOnChange();
}

function appendAsterixToMandatoryFields() {
	$(".mandatory > fieldset > legend").append('<span class="asterix" aria-hidden="true"> *</span>');
}

function getSplitIndexForPhoneNumber(val) {
	return val.indexOf(") ") < 0 ?
			(val.indexOf(")") < 0 ?
				0 : val.indexOf(")")) + 1
			: val.indexOf(") ") + 2;
}

//Start loading animation
function startLoadingAnimation($input) {
	$input.attr("disabled", "disabled");
	$input.parent().addClass("loading");	
}

//End loading animation
function endLoadingAnimation($input) {
	$input.removeAttr("disabled", "disabled");
	$input.parent().removeClass("loading");	
}

function autoFillPostalCode() {
	//Bind on keyup event, so that city/place is autofilled based on postal code
	$(".input-postalcode").on("keyup change", function() {
		var $inputPanel = $(this).closest(".input-panel");
		var $selectLand = $inputPanel.find(".select-land").first();
		if($selectLand) {			
			var countryCode = $selectLand.val().toLowerCase();
			var postalCode = $(this).val();

			var $inputPlace = $inputPanel.find(".input-place").first();
			
			$.getJSON("https://fraktguide.bring.no/fraktguide/api/postalCode.json?country=" + countryCode + "&pnr=" + postalCode, function(json){		
				if(json.valid && json.result) {
					//Autofill with result from API
					$inputPlace.val(json.result);
				}
	    	});	
		}
 	});
	
	//Toggles pattern for the postal code input
	var togglePattern = function($sel) {
		var $formGroup = $sel.closest(".form-group");
		var $postalCodeInputs = $formGroup.find(".input-postalcode");
		
		console.log("TOGGLE");
		
		var countryCode = $sel.val().toUpperCase();
		if (countryCode == "NO" || countryCode == "SJ" || countryCode == "SE" || countryCode == "DK" || countryCode == "FI" || countryCode == "DE" || countryCode == "FR" || countryCode == "LI" || countryCode == "EE" || countryCode == "LV") {
			$postalCodeInputs.attr("pattern", "[0-9]*"); //iOS
			$postalCodeInputs.attr("inputmode", "numeric"); //Android
		}
		else {
			$postalCodeInputs.removeAttr("pattern"); //iOS
			$postalCodeInputs.removeAttr("inputmode"); //Android
		}
	}
	
	//Bind on change event, so that pattern on phones can be updated according to
	//postal code format.
	$(".select-land").on("change", function() {
		togglePattern($(this));
 	});
	
	//Toggle according to current country
	$.each($(".select-land"), function() {
		togglePattern($(this));
	});
}

//Uses the api provided by restcountries.eu
function autoFillCountryCallingCode() {
	var setCountryCode = function($selects) {
		if(!$selects.length) return;
		
		$.each($selects, function() {
			var $sel = $(this);
			var code = $sel.val().toLowerCase();
		
			$.getJSON("https://restcountries.eu/rest/v2/alpha/" + code, function(result){
				
				//Prepend country code to all phone inputs in  the current input-panel
				var $formGroup = $sel.closest(".form-group");
				var $phoneInputs = $formGroup.find('input[type="tel"]');

				$.each($phoneInputs, function() {
					var val = $(this).val()
					var splitIndex = getSplitIndexForPhoneNumber(val);
					if (val.length == 0 || splitIndex == val.length) { //When input is empty
						$(this).val("(+" + result.callingCodes[0] + ") ");
					}
					else {
						//$(this).val("(+" + result.callingCodes[0] + ") " + val.substring(splitIndex, val.length));
						console.log("Skipping auto fill of country code. Value is: " + $(this).val() + " result returned by API is " + result.callingCodes[0] + " splitIndex is: " + splitIndex + " val.length is : " + val.length);
					}
				});
			});
		});
	};

	//Bind on change event, so that country code is updated
	$(".select-land").on("change", function() {
		setCountryCode($(this));
 	});

	//Update the country code for the country currently selected
 	setCountryCode($(".select-land"));
}

function checkAndAutoFillFromOrgNr($orgNrInput) {
	var $errorMessage = $orgNrInput.parent().find(".digiforms_validation_message");
	var $validationField = $orgNrInput.closest(".input-panel").find("#orgnumber-valid");

	var orgNr = removeWhiteSpaces($orgNrInput.val());
	if (orgNr.length == 9) {
		var $formGroup = $orgNrInput.closest(".form-group");

		//Company name
		var $companyNameInput = $formGroup.find(".input-company-name");
		var companyName = "";

		//Postadresse
		var $countryInput = $formGroup.find(".select-land");
		var country = $countryInput.val();
		var $streetInput = $formGroup.find(".input-street");
		var street = "";
		var $postalCodeInput = $formGroup.find(".input-postalcode");
		var postalCode = "";
		var $placeInput = $formGroup.find(".input-place");
		var place = "";
		
		//Start loading animation
		startLoadingAnimation($companyNameInput);
		startLoadingAnimation($countryInput);
		startLoadingAnimation($streetInput);
		startLoadingAnimation($postalCodeInput);
		startLoadingAnimation($placeInput);
		
		$.getJSON("https://data.brreg.no/enhetsregisteret/enhet/" + orgNr + ".json", function(result) {
			if (result.status != 400) {
				companyName = result.navn;
				country = result.forretningsadresse.landkode;
				street = result.forretningsadresse.adresse;
				postalCode = result.forretningsadresse.postnummer;
				place = result.forretningsadresse.poststed;
				$validationField.val("true");
				clearErrormessage($placeInput);
				clearErrormessage($orgNrInput);
			}
		}).fail(function(jqxhr) {
			console.log("UNDERENHET - Status is: " + jqxhr.status);
		    if (jqxhr.status == 404) {
		       	//Prøv å slå mot underenhetsregisteret istedenfor: (kanskje ikke best practice?)
				$.getJSON("https://data.brreg.no/enhetsregisteret/underenhet/" + orgNr + ".json", function(result) {
					if (result.status != 400) {
						companyName = result.navn;
						country = result.beliggenhetsadresse.landkode;
						street = result.beliggenhetsadresse.adresse;
						postalCode = result.beliggenhetsadresse.postnummer;
						place = result.beliggenhetsadresse.poststed;
						$validationField.val("true");
						clearErrormessage($placeInput);
						clearErrormessage($orgNrInput);
					}
					else {
						$errorMessage.text("Ugyldig organisasjonsnummer");
						$validationField.val("false");
					}
					
					//Remove loading animation
					endLoadingAnimation($companyNameInput);
					endLoadingAnimation($countryInput);
					endLoadingAnimation($streetInput);
					endLoadingAnimation($postalCodeInput);
					endLoadingAnimation($placeInput);
					
					$companyNameInput.val(companyName);
					$countryInput.val(country);
					$streetInput.val(street);
					$postalCodeInput.val(postalCode);
					$placeInput.val(place);
				});
		    }
		    else {
				//Remove loading animation
				endLoadingAnimation($companyNameInput);
				endLoadingAnimation($countryInput);
				endLoadingAnimation($streetInput);
				endLoadingAnimation($postalCodeInput);
				endLoadingAnimation($placeInput);
				
				$companyNameInput.val(companyName);
				$countryInput.val(country);
				$streetInput.val(street);
				$postalCodeInput.val(postalCode);
				$placeInput.val(place);
				
		    	$errorMessage.text("Ugyldig organisasjonsnummer");
		    	$validationField.val("false");
		    }
		}).always(function() {
				//Remove loading animation
				endLoadingAnimation($companyNameInput);
				endLoadingAnimation($countryInput);
				endLoadingAnimation($streetInput);
				endLoadingAnimation($postalCodeInput);
				endLoadingAnimation($placeInput);
				
				$companyNameInput.val(companyName);
				$countryInput.val(country);
				$streetInput.val(street);
				$postalCodeInput.val(postalCode);
				$placeInput.val(place);
		});
	}
	else {
		if (orgNr.length > 0) $errorMessage.text("Må være 9 siffer");
		else $errorMessage.text("Må fylles ut");
		$validationField.val("false");
	}
}

function autoFillFromOrgNr() {
	$(".input-org-number").on("change paste input", function() {
		checkAndAutoFillFromOrgNr($(this));
	});
}

function bindEventsThatCallsExternalAPIs() {
	autoFillPostalCode();
	autoFillCountryCallingCode();
	autoFillFromOrgNr();
}

function removeWhiteSpaces(str) {
	var subStrings = str.split(" ");
	var newStr = "";
	for(var i=0; i < subStrings.length; i++) {
		newStr += subStrings[i].trim();
	}
	return newStr;
}

function validationMOD11(val, weightNumber, ignoreLength) {
	var number = removeWhiteSpaces(val);

	var sum = 0;
	for(var i=0; i < number.length - 1; i++) {
		//console.log(number.charAt(i) + " * " + weightNumber.charAt(i) + " = " + (number.charAt(i) * weightNumber.charAt(i)));
		sum += number.charAt(i) * weightNumber.charAt(i);
	}

	var reminderMOD11 = sum % 11;

	//Calculate control number (norwegian account numbers can't have a reminder of 1)
	var calculatedControllNumber = reminderMOD11 == 0 ? 0 : 11 - reminderMOD11;
	
	//Check if the calculated control number is equal to the given one ()
	if (calculatedControllNumber != number[number.length - 1] && (ignoreLength || number.length == 11)) {
		//console.log("not valid. Calculated: " + calculatedControllNumber + " actual: " + number[number.length - 1]);
		return false;
	}
	else if (ignoreLength || number.length == 11) {
		//console.log("valid!");
		return true;
	}
	else {
		//console.log("invalid, incorrect length!");
		return false;
	}
}

function validation() {

	var findMyHiddenBrother = function($input) {
		var $validationField = $input.closest(".label_control").parent().parent().find("input[type=hidden]:first");
		return $validationField;
	}

	//Validation for norwegian account numbers
	var validateAccountNo = function($element) {
		if ($element.val().length > 0 && $element.val().length < parseInt($element.attr("maxlength"))) {
			var $errorMessage = $element.parent().find(".digiforms_validation_message");
			$errorMessage.text("Må være 11 siffer");
		}
		var valid = validationMOD11($element.val(), "5432765432", false);
		var $validationField = findMyHiddenBrother($element);
		$validationField.val(valid);
		if (valid) {
			clearErrormessage($element[0]);
		}
		else if (!valid && $element.val().length == parseInt($element.attr("maxlength"))) {
			var $errorMessage = $element.parent().find(".digiforms_validation_message");
			$errorMessage.text("Ugyldig kontonummer");
		}
	}
	
	var $accountInputs = $("input.numeric-text.account-mask");
	$accountInputs.on("change", function() {
		validateAccountNo($(this));
	});

	$.each($accountInputs, function() {
		validateAccountNo($(this));
	});

	//Validation for VPS account numbers
	var validateVPS = function($element) {
		var valTrimmed = removeWhiteSpaces($element.val());
		var $validationField = findMyHiddenBrother($element);

		if (valTrimmed.length == 12) {
			$validationField.val(true);
			clearErrormessage($element[0]);
		}
		else {
			$validationField.val(false);
			var $errorMessage = $element.parent().find(".digiforms_validation_message");
			if (valTrimmed.length > 0) {
				$errorMessage.text("Må være 12 siffer");
			}
		}
	}
	var $vpsAccountInputs = $("input.numeric-text.vps-account-mask");
	$vpsAccountInputs.on("change", function() {
		validateVPS($(this));
	});

	$.each($vpsAccountInputs, function() {
		validateVPS($(this));
	});

	//Validation for norwegian input social security numbers
	var validateSocialSecurityNumberNo = function($element) {
		if($element.val().length > 0 && $element.val().length < parseInt($element.attr("maxlength"))) {
			var $errorMessage = $element.parent().find(".digiforms_validation_message");
			$errorMessage.text("Må være 11 siffer (DDMMÅÅXXXXX)");
		}
		else {
			var valid1 = validationMOD11($element.val().substring(0, 10), "376189452", true); //1st Kontrollsiffer
			var valid2 = validationMOD11($element.val(), "5432765432", false); //Second control number
			var $validationField = findMyHiddenBrother($element);
			$validationField.val(valid1 && valid2);
			if(!(valid1 && valid2) && $element.val().length > 0) {
				var $errorMessage = $element.parent().find(".digiforms_validation_message");
				$errorMessage.text("Ugyldig fødselsnummer");
			}
		}
	}
	
	var $socialSecurityNumberNoInputs = $("input.numeric-text.input-social-security-number-no");
	$socialSecurityNumberNoInputs.on("change", function() {
		validateSocialSecurityNumberNo($(this));
	});
	
	$.each($socialSecurityNumberNoInputs, function() {
		validateSocialSecurityNumberNo($(this));
	});

	//Checks and sets validationmessage depending on feedback from 
	//External API (brreg)
	var $orgNumberInputs = $(".input-org-number");
	if($orgNumberInputs.length) checkAndAutoFillFromOrgNr($orgNumberInputs);

	//Validate lei-number
	var validateNValidateInputs = function($element) {
		var $validationInput = findMyHiddenBrother($element);
		var valTrimmed = removeWhiteSpaces($element.val());
		if(valTrimmed.length == 0 || valTrimmed.length == parseInt($element.attr("maxlength"))) {
			$validationInput.val(true);
		}
		else {
			$validationInput.val(false);
		}
	}
	
	var $nValidateInputs = $("input.n-validate");
	$nValidateInputs.on("change", function() {
		validateNValidateInputs($(this));
	});
	
	$.each($nValidateInputs, function() {
		validateNValidateInputs($(this));
	});
	
	$("#knapp_neste").on("click", function() {
		//Validate account numbers
		$.each($accountInputs, function() {
			validateAccountNo($(this));
		});

		//Validate VPS account numbers
		$.each($vpsAccountInputs, function() {
			validateVPS($(this));
		});
		
		//Validate social security numbers
		$.each($socialSecurityNumberNoInputs, function() {
			validateSocialSecurityNumberNo($(this));
		});
		
		//Validate lei-number
		$.each($nValidateInputs, function() {
			validateNValidateInputs($(this));
		});
	});
}

function setOffset($element) {
	var widthOffset = ($element.width() * 1.5) + "px";
	$element.attr("style", "padding-left: calc(50% - " + widthOffset + ")");
}

function getFirstError($root) {
	return $root.find(".digiforms_validation_message:first");
}

function scrollToFirstError() {
	//if (window.location.href.indexOf("#id-") < 0 && window.location.href.indexOf("#container-") < 0) {
	if (window.location.href.indexOf("#") < 0) {
		var $firstError = getFirstError($("body")).closest(".label_control").parent();

		//Check if the error is linked to an input
		if (!$firstError.length) {
			//If not, it's linked to a fieldset. And we look for that instead.
			$firstError = $(".digiforms_validation_message:first").closest("fieldset");
		}
		scrollTo($firstError, 1000);
	}
}

function initFileDownloadLinks() {
	var sessionTag = $("#frm").attr("action").split("?")[1];
	$.each($(".file-download"), function() {
		$(this).attr("href", $(this).attr("href") + sessionTag);
	});
}

function setAriaAttributesForFileDownloadButtons() {
	$.each($(".file-download"), function() {
		$(this).attr("aria-label", "Åpne");
	});
}

function adjustErrorMessagesForFileUpload() {
	var $errorMsgContainer = $("label[for='vedlegg-btn']").parent().siblings("div:first");
	if($errorMsgContainer.length) {
		$errorMsgContainer.css("margin-top", "5px");
		var $errorMsgText = $errorMsgContainer.find("span.digiforms_validation_message");
		var allowedValues = $errorMsgText.text().substring($errorMsgText.text().indexOf("[") + 1, $errorMsgText.text().indexOf("]")).trim();
		if($errorMsgText.text().indexOf("File type") >= 0) {
			$errorMsgText.text("Beklager, filtypen er ikke støttet! Vi trenger en av følgende filtyper: " + allowedValues + ".");
		}
		else if ($errorMsgText.text().indexOf("File is") >= 0) {
			$errorMsgText.text("Beklager, filen er for stor! Den kan ikke være større enn " + allowedValues + ".");
		}
	}
}

function initFileDownloads() {
	initFileDownloadLinks();
	setAriaAttributesForFileDownloadButtons();
	adjustErrorMessagesForFileUpload();
	$("#button_upload_updatexml").attr("aria-hidden", "true");
}

function setAriaAttributesForDeleteButtons() {
	$.each($(".btn-delete"), function() {
		var $deletableElement = $(this).closest(".deletable");
		var $description = $deletableElement.find(".aria-description");
		var $item;
		if ($(this).closest(".load-container").length) {
			var n = $(this).attr("id").substring($(this).attr("id").indexOf("_"));
			$item = $deletableElement.find("#rettighetshaver" + n);
		}
		else {
			$item = $description.find(".item");
		}
		if ($item.length) {
			$(this).attr("aria-controls", $item.attr("id"));
			$(this).attr("aria-describedby", $description.attr("id"));
		}
	});
}

function initDeleteButtons() {
	setAriaAttributesForDeleteButtons();
	
	$.each($(".load-container .btn-delete"), function() {
		if ($(this).attr("onclick").indexOf("var callback") > -1) {
			return;
		}
		var correspondingAccordionId = $(this).attr("aria-controls");
		var callback = $(this).attr("onclick").replace("javascript:", "");
		$(this).attr("onclick", "var callback = function () { " + callback + "};scrollToElementAddedByAJAX = false; $('#" + correspondingAccordionId + "').parent().fadeOut(400, callback); ");
	});
}

//Disables add buttons when maxium number of
//elements has been added
function disableAddButtonsWhenMaxIsReached() {
	var $loadContainer =  $(".load-container.max-6");
	if($loadContainer.find(".accordion-container").length > 5) {
		$loadContainer.siblings(".add-content").prop("disabled", true);
		if(!$("#button-disabled-description").length) {
			$loadContainer.append("<p id='button-disabled-description' class='text-center'><strong>Du kan ikke legge til flere rettighetshavere.</strong></p>");	
		}
	}
	else {
		$loadContainer.siblings(".add-content").prop("disabled", false);
	}
}

function initAJAXUpdateElements() {
	$.each($(".triggers-ajax-update-scroll-to-first"), function() {
		var doBeforeOnchange = "scrollToElementAddedByAJAX = true;";
		if($(this).attr("onchange").indexOf(doBeforeOnchange) > -1) {
			return;
		}
		var newOnchange = doBeforeOnchange + $(this).attr("onchange").replace("javascript:", "");
		$(this).attr("onchange", newOnchange)
	});
}